# Generated by Django 4.0.3 on 2024-05-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_answer_modify_date_question_modify_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='modify_date',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
